apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      labels:
        app: kube-project
    spec:
      volumes: # Define volume
          - name: shared-image
            persistentVolumeClaim:
              claimName: image-claim
      containers:
        - name: backend
          image: ipegii/kube-project-backend:0.1.7
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
        - name: frontend
          image: ipegii/kube-project-frontend:0.1.9
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files