apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercise-namespace
  name: exercise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-app
  template:
    metadata:
      labels:
        app: exercise-app
    spec:
      volumes: # Define volume
        - name: config-volume
          configMap:
            name: exercise-configmap
     #     - name: shared-image
     #       persistentVolumeClaim:
     #         claimName: image-claim
      containers:
        - name: file-serve
          image: ipegii/kube-project-file-serve:0.4.4
          envFrom:
          - secretRef:
              name: postgres-credentials
          env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: exercise-configmap
                key: HOST
   #       volumeMounts: # Mount volume
   #       - name: shared-image
   #         mountPath: /usr/src/app/files
        - name: file-fetch
          image: ipegii/kube-project-file-fetch:0.1.5
          envFrom:
          - secretRef:
              name: postgres-credentials
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: exercise-configmap
                key: MESSAGE
   #       volumeMounts: # Mount volume
   #       - name: shared-image
   #         mountPath: /usr/src/app/files