apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercise-namespace
  name: ingress-wildcard-host
spec:
  rules:
   - http:
      paths:
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pingpong-svc
            port:
              number: 80
   - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: two-container-svc
            port:
              number: 80
