apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercise-namespace
  name: image-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi