apiVersion: v1
kind: Service
metadata:
  namespace: exercise-namespace
  name: two-container-svc
spec:
  type: ClusterIP
  selector:
    app: two-container
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000