apiVersion: v1
kind: Service
metadata:
  namespace: exercise-namespace
  name: exercise-back-svc
spec:
  type: ClusterIP
  selector:
    app: exercise-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001